### ISSUE TITLE
Error after updating from 1.11.0 to 1.12.1

### ISSUE THREAD

**Issue by etx** [FusionAuth/fusionauth-node-client#7]
I'm seeing this error after updating from 1.11.0 to 1.12.1 today.

`this._startAnonymous.authorization is not a function`

The lib instantiates fine but throws the error when trying to call `retrieveTenant()` 

I checked the docs to see if anything else had changed, but I'm not seeing anything.

**Comment by tyduptyler13** [comment]
Thank you for reporting the issue. I fixed our client and should have a patch released soon.

**Comment by tyduptyler13** [comment]
The patch is released on [npm](https://www.npmjs.com/package/@fusionauth/node-client/v/1.12.2). You can change your version to `1.12.2` and everything should work.

**Comment by etx** [comment]
Thanks! I'll try it out asap

**Comment by lilyannh** [comment]
@tyduptyler13 FYI this is broken again in 1.12.3 (as well as the issue from #6).  Downgrading to 1.12.2 works fine.

**Comment by robotdan** [comment]
@snazzypants What error are you getting?  I downloaded 1.12.3 from https://www.npmjs.com/package/@fusionauth/node-client and it seems ok.

**Comment by lilyannh** [comment]
npm install @fusionauth/node-client@latest

First:
```
 ReferenceError: this_startAnonymous is not defined
    at FusionAuthClient._start (C:\jnl\api\node_modules\@fusionauth\node-client\lib\FusionAuthClient.js:3501:5)
    at Promise (C:\jnl\api\node_modules\@fusionauth\node-client\lib\FusionAuthClient.js:1140:12)
    at tryCallTwo (C:\jnl\api\node_modules\promise\lib\core.js:45:5)
    at doResolve (C:\jnl\api\node_modules\promise\lib\core.js:200:13)
    at new Promise (C:\jnl\api\node_modules\promise\lib\core.js:66:3)
    at FusionAuthClient.login (C:\jnl\api\node_modules\@fusionauth\node-client\lib\FusionAuthClient.js:1139:12)
    at Object.login (C:\jnl\api\src\services\fusionAuth.ts:11:16)
    at handler (C:\jnl\api\src\routes\auth\login.ts:11:11)
    at module.exports.internals.Manager.execute (C:\jnl\api\node_modules\@hapi\hapi\lib\toolkit.js:41:33)
    at Object.internals.handler (C:\jnl\api\node_modules\@hapi\hapi\lib\handler.js:46:48)
```

Then, fixing the typo (this_startAnonymous to this._startAnonymous):

```
  TypeError: this._startAnonymous.authorization is not a function
    at FusionAuthClient._start (C:\jnl\api\node_modules\@fusionauth\node-client\lib\FusionAuthClient.js:3501:33)
    at Promise (C:\jnl\api\node_modules\@fusionauth\node-client\lib\FusionAuthClient.js:1140:12)
    at tryCallTwo (C:\jnl\api\node_modules\promise\lib\core.js:45:5)
    at doResolve (C:\jnl\api\node_modules\promise\lib\core.js:200:13)
    at new Promise (C:\jnl\api\node_modules\promise\lib\core.js:66:3)
    at FusionAuthClient.login (C:\jnl\api\node_modules\@fusionauth\node-client\lib\FusionAuthClient.js:1139:12)
    at Object.login (C:\jnl\api\src\services\fusionAuth.ts:11:16)
    at handler (C:\jnl\api\src\routes\auth\login.ts:11:11)
    at module.exports.internals.Manager.execute (C:\jnl\api\node_modules\@hapi\hapi\lib\toolkit.js:41:33)
    at Object.internals.handler (C:\jnl\api\node_modules\@hapi\hapi\lib\handler.js:46:48)
```
